name: medisync
description: "A AI powewrered health care assistant"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  shared_preferences: ^2.3.5
  http: ^1.3.0
  google_fonts: ^6.2.1
  animate_do: ^3.3.4
  google_sign_in: ^6.2.2
  curved_navigation_bar: ^1.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  geolocator: ^13.0.2
  convert: ^3.1.2
  flutter_map: ^8.0.0
  latlong2: ^0.9.1
  url_launcher: ^6.3.1
  intl: ^0.20.2
  flutter_markdown: ^0.7.6+1
  markdown: ^7.3.0
  fl_chart: ^0.70.2
  photo_view: ^0.15.0
  file_picker: ^8.3.2
  flutter_animate: ^4.5.2
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  
  assets:
    - lib/assets/logo.png
    - lib/assets/google_icon.png
    - lib/assets/chatbot_logo.png

# Move flutter_launcher_icons configuration outside of flutter section
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.png"  # Path to your logo file